// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	model "psql-mcp-registry/internal/model"

	mock "github.com/stretchr/testify/mock"

	pg "psql-mcp-registry/internal/pg"
)

// ClientFactory is an autogenerated mock type for the ClientFactory type
type ClientFactory struct {
	mock.Mock
}

// CreateClient provides a mock function with given fields: instance
func (_m *ClientFactory) CreateClient(instance model.Instance) (pg.ClientInterface, error) {
	ret := _m.Called(instance)

	if len(ret) == 0 {
		panic("no return value specified for CreateClient")
	}

	var r0 pg.ClientInterface
	var r1 error
	if rf, ok := ret.Get(0).(func(model.Instance) (pg.ClientInterface, error)); ok {
		return rf(instance)
	}
	if rf, ok := ret.Get(0).(func(model.Instance) pg.ClientInterface); ok {
		r0 = rf(instance)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pg.ClientInterface)
		}
	}

	if rf, ok := ret.Get(1).(func(model.Instance) error); ok {
		r1 = rf(instance)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewClientFactory creates a new instance of ClientFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClientFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClientFactory {
	mock := &ClientFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
