// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	model "psql-mcp-registry/internal/model"

	mock "github.com/stretchr/testify/mock"

	pg "psql-mcp-registry/internal/pg"
)

// Registry is an autogenerated mock type for the Registry type
type Registry struct {
	mock.Mock
}

// AddInstanceToRegistry provides a mock function with given fields: instance
func (_m *Registry) AddInstanceToRegistry(instance model.Instance) error {
	ret := _m.Called(instance)

	if len(ret) == 0 {
		panic("no return value specified for AddInstanceToRegistry")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.Instance) error); ok {
		r0 = rf(instance)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetInstanceClient provides a mock function with given fields: instance
func (_m *Registry) GetInstanceClient(instance model.Instance) pg.ClientInterface {
	ret := _m.Called(instance)

	if len(ret) == 0 {
		panic("no return value specified for GetInstanceClient")
	}

	var r0 pg.ClientInterface
	if rf, ok := ret.Get(0).(func(model.Instance) pg.ClientInterface); ok {
		r0 = rf(instance)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pg.ClientInterface)
		}
	}

	return r0
}

// NewRegistry creates a new instance of Registry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *Registry {
	mock := &Registry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
