// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	model "psql-mcp-registry/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// InstanceRegistry is an autogenerated mock type for the InstanceRegistry type
type InstanceRegistry struct {
	mock.Mock
}

// AddInstanceToRegistry provides a mock function with given fields: instance
func (_m *InstanceRegistry) AddInstanceToRegistry(instance model.Instance) error {
	ret := _m.Called(instance)

	if len(ret) == 0 {
		panic("no return value specified for AddInstanceToRegistry")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.Instance) error); ok {
		r0 = rf(instance)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewInstanceRegistry creates a new instance of InstanceRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInstanceRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *InstanceRegistry {
	mock := &InstanceRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
